# Generated by Django 5.0.2 on 2024-02-18 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babka', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tovar',
            options={'ordering': ['-publish'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
