# Generated by Django 5.0.2 on 2024-02-18 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babka', '0002_alter_tovar_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='cost',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$')]),
        ),
    ]
